FROM registry.suse.com/bci/bci-base:15.6 AS builder

COPY *.rpm /tmp
COPY *.tar.gz *.zip /
WORKDIR /tmp
RUN zypper --non-interactive --no-gpg-checks install gcc43.rpm gcc43-c++.rpm libstdc++43-devel.rpm cpp43.rpm xauth.rpm
RUN zypper --non-interactive install gcc43 gcc43-c++ make automake makeinfo git gawk wget libicu-devel mlocate vim unzip cmake xz meson patch libtool gtk-doc libatk-1_0-0 libICE-devel libSM-devel libXt-devel gtk2 gtk2-devel dejavu-fonts
ENV CC=gcc-4.3
ENV CXX=g++-4.3
ENV PERL5LIB=.
RUN ln -s /usr/bin/gcc-4.3 /usr/bin/gcc && \
    ln -s /usr/bin/g++-4.3 /usr/bin/g++


WORKDIR /
RUN tar -xvf openssl-0.9.8k.tar.gz
WORKDIR /openssl-0.9.8k
RUN ./config && \
    make && \
    make install_sw && \
    ln -s /usr/local/ssl/lib/lib* /usr/lib64/


WORKDIR /
RUN tar -xvf db-4.7.25.NC.tar.gz
WORKDIR /db-4.7.25.NC/build_unix
RUN ../dist/configure --enable-cxx && \
    make -j"$(($(nproc) + 1))" && make install && \
    ln -s /usr/local/BerkeleyDB.4.7/lib/* /usr/lib64/



WORKDIR /
RUN tar -xvf macros-util-macros-1.3.0.tar.gz
WORKDIR /macros-util-macros-1.3.0
RUN sed -i '24i m4_pattern_allow([AS_HELP_STRING])' configure.ac  && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install


WORKDIR / 
RUN tar -xvf libxtrans-xtrans-1.0.2.tar.gz
WORKDIR /libxtrans-xtrans-1.0.2
RUN sed -i '24i m4_pattern_allow([AS_HELP_STRING])' configure.ac && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install


WORKDIR /
RUN ls -ltrh
RUN tar -xvf pango-1.24.5.tar.gz
RUN mv /usr/include/freetype2 /opt/freetype2_bak && \
    mkdir -p /usr/local/include/freetype1 && \
    mkdir -p /usr/local/include/freetype
RUN unzip freetype.zip
RUN cp -r /freetype-master/include/freetype/* /usr/local/include/freetype1 && \
    cp -r /freetype-master/include/*.h /usr/local/include/freetype1 && \
    cp -r /usr/local/include/freetype1/* /usr/local/include/freetype
WORKDIR /pango-1.24.5
RUN CPPFLAGS="-I/usr/local/include/freetype1" ./configure && \
    make -j"$(($(nproc) + 1))" && \
    make install && \
    mv /opt/freetype2_bak /usr/include/freetype2 && \
    cp -r /pango-1.24.5/pango/.libs/* /usr/lib64/

WORKDIR /
RUN unzip v2.8.9.zip
WORKDIR /wxWidgets-2.8.9
RUN ./autogen.sh && \
    find . -type f -exec sed -i 's/GSocket/wxGSocket/g' {} \; && \
    find . -type f -exec sed -i 's/typedef struct _GSocket/typedef struct _wxGSocket/' {} \; && \
    find . -type f -exec sed -i 's/class GSocket/class wxGSocket/' {} \; && \
    CXXFLAGS="-fPIC -fpermissive" CFLAGS="-fPIC -fpermissive" ./configure --enable-unicode --enable-debug --prefix=/usr/local/wxwidgets  --with-gtk --enable-shared --enable-monolithic && \
    ln -s /usr/lib64/libjpeg.so.8 /usr/lib64/libjpeg8.so && \
    unlink /usr/lib64/libjpeg.so && \
    ln -s /usr/lib64/libjpeg.so.8.2.2 /usr/lib64/libjpeg.so && \
    CXXFLAGS="-fPIC -fpermissive" CFLAGS="-fPIC" make -j"$(($(nproc) + 1))" LDFLAGS="-lpangocairo-1.0 -lX11 -lcairo -ljpeg8" && \
    make install && \
    ldconfig 


WORKDIR /
RUN tar -xvf boost_1_40_0.tar.gz
ENV BOOST_ROOT=/boost_1_40_0
WORKDIR /boost_1_40_0
RUN chmod +x bootstrap.sh && \
    ./bootstrap.sh && \
    ./bjam -j"$(($(nproc) + 1))" install || echo 1


WORKDIR /
RUN unzip v0.2.0_patched.zip
WORKDIR /bitcoin_core_history-0.2.0_patched
RUN mkdir -p obj/nogui && \
    zypper --non-interactive install dos2unix && \
    dos2unix * && \
    make -f makefile.mocacinno bitcoin CFLAGS="-I/usr/local/wxwidgets/include/wx-2.8/ -I/usr/local/wxwidgets/lib/wx/include/gtk2-unicode-debug-2.8 -I/usr/local/lib/ -I/usr/lib64/wx/include/gtk2-unicode-debug-2.9 -I/openssl-0.9.8k/include -I/usr/local/wxwidgets/lib/ -I/usr/local/BerkeleyDB.4.7/include -I/wxWidgets-2.8.9/lib -fpermissive -D_FILE_OFFSET_BITS=64 -D__WXDEBUG__ -DWXUSINGDLL -D__WXGTK__ -pthread -march=x86-64 -mtune=generic"
RUN strip bitcoin
RUN ln -s /usr/local/wxwidgets/lib/libwx_gtk2ud-2.8.so.0 /usr/lib64/libwx_gtk2ud-2.8.so.0
RUN ln -s /bitcoin_core_history-0.2.0_patched/bitcoin /usr/local/bin
