name: Build and Publish Docker Images

on:
  push:
    branches:
      - 'v*.*'
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:cache,mode=max
        provenance: mode=max
        sbom: true
        outputs: type=image,name=ghcr.io/${{ github.repository_owner }}/${{ github.repository }},digest=true

    - name: Install Cosign v2.2.2
      uses: sigstore/cosign-installer@v3.3.0
      with:
        cosign-release: 'v2.2.2'

    - name: Cosign Keyless Sign (by digest)
      env:
        COSIGN_EXPERIMENTAL: "1"
      run: |
        cosign sign --yes ghcr.io/${{ github.repository_owner }}/${{ github.repository }}@${{ steps.build.outputs.digest }}

    - name: Generate SBOM with Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }} -o spdx-json > /tmp/sbom.json

    - name: Cosign Attest SBOM
      env:
        COSIGN_EXPERIMENTAL: "1"
      run: |
        cosign attest --yes \
          --type spdxjson \
          --predicate /tmp/sbom.json \
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}@${{ steps.build.outputs.digest }}
