name: Build and Publish Docker Images

on:
  push:
    branches:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build and push multi-platform Docker image (Linux and Windows x86)
      - name: Build and Push Docker image for Linux and Windows
        run: |
          docker buildx build \
            --platform linux/amd64,windows/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }} \
            --push .
